services:
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: shop
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data

  zipkin:
    image: openzipkin/zipkin:3
    ports:
      - "9411:9411"

  shop:
    image: nelsonvillam/shop:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/shop?authSource=admin
      ZIPKIN_URL: http://zipkin:9411
    depends_on:
      - mongo
      - redis
      - zipkin

volumes:
  mongo-data:
  redis-data:
